### ISSUE TITLE
 A parameter cannot be found that matches parameter name 'PolicyFile'.

### ISSUE THREAD

**Issue by marian-craciunescu** [Fortigi/ConditionalAccess#1]
PS /home/mcraciun>   Set-ConditionalAccessPolicy -Id $Exists.id -AccessToken $AccessToken -PolicyFile $Policy.FullName -PathConvertFile
Set-ConditionalAccessPolicy: A parameter cannot be found that matches parameter name 'PolicyFile'.

**Comment by marian-craciunescu** [comment]
this is becasue the old version of powershell module is pushed

**Comment by WimvandenHeijkant** [comment]
Hi Marian, you are correct the version on GitHub is not the same as the version in PowerShell Gallery we have not updated the PowerShell Gallery version to the latest's yet. So make sure to use the version from GitHub..
